### PR TITLE
RNVideoChat: PushNotificationsService, VoIP push notifications, Call Kit

### PR DESCRIPTION
**Pull request by DaveLomber**
What's done:

- [x] PushNotificationsService class
- [x] normal push notifications subscription 
- [x] VoIP push notifications subscription 
- [x] iOS push notifications project configuration
- [x] Send push notifications when initiate a call 
- [ ] Android push notifications project configuration
- [ ] Call Kit integration
- [ ] Show Call Kit screen when receive incoming call
- [ ] Proper accept call flow with  Call Kit

### CODE REVIEW

**Comment by meosieudang** [comment]
please login account cube on native before send push voip @DaveLomber

**Comment by DaveLomber** [comment]
@meosieudang could you please explain in more details this comment https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/200#issuecomment-768206237

**Comment by mikeangelsilva** [comment]
Hi, does the callkit integration works in this pr?

**Comment by DaveLomber** [comment]
@mikeangelsilva the work is still ongoing 
Will share more details later this week

**Comment by CMLCNL** [comment]
Because the callkit is displayed, but we are not yet connected to the chat. Stupid situations occur. Callkit can't turn off and it rings forever.

**Comment by meosieudang** [comment]
@DaveLomber , any news?

**Comment by gwenoleR** [comment]
@DaveLomber any news ?

**Comment by arghyaMatrix** [comment]
@DaveLomber any update in this feature?

**Comment by andybui090** [comment]
any update

**Comment by DaveLomber** [comment]
closed in favour of https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/301

**Comment by DaveLomber** [comment]
Call Kit implementation for iOS is finished here https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/301

**Pull request closed without merging**
