### PR TITLE
react-native rundroid not working issue resolved

### PR DESCRIPTION
**Pull request by gilons**

### CODE REVIEW

**Comment by DaveLomber** [comment]
Hi @gilons 

thank you for the PR provided! 

I just tried it, but got the following errors:


FAILURE: Build failed with an exception.

```
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-fetch-blob.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fetch-blob: None of the consumable configurations have attributes.
   > Could not resolve project :@react-native-community_async-storage.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@react-native-community_async-storage: None of the consumable configurations have attributes.

```

it seems we do not have these libs in package.json hence the issues occur

Please let me know for what purpose we need them in grade files

**Comment by gilons** [comment]
They appear to be be used in your app.

I will make a new or where I will add them in them in the package.json

**Comment by gilons** [comment]
Manually I mean because they are supposed to be added automatically as I
ran npm install .

**Comment by DaveLomber** [comment]
closed as a new code sample is released

**Pull request closed without merging**
