### PR TITLE
P2p callkeep

### PR DESCRIPTION
**Pull request by Kachanov-dev**

### CODE REVIEW

**Comment by Kachanov-dev** [comment]
Проблемы:
Мы закрываем полностью апу,  затем шлеп push-notification  из админки. В андройд студии мы можем увидеть получения пуша "onMessageReceived".  Проблема заключается в том, что при получении пуша мы не можем поднять наше приложение. Либа RN-push-notification не предоставляет лисенера, для прослушки в  background пушей в нашем приложении.

**Comment by Kachanov-dev** [comment]
> Hi, im trying to use this code in my project.
> 
> but when i try to call a sample user. the callkit UI is not showing.
> i expect the callkit will show once the other user initiate a call.
> or am i wrong?
> 
> Thank you :)

Hi @mikeangelsilva , this PR is under development, this isn't the final stage.

**Comment by stephanoparaskeva** [comment]
How can I contact you?

I would like to pay someone to help me implement ConnectyCube Video + CallKeep + Wake App From Background + Notifications + Messages in 1 template app.

I already have implemented ConnectyCube + Callkeep.

I need help and would love to get in touch and talk about paid/free work whichever suits you?

**Comment by ccvlad** [comment]
> How can I contact you?
> 
> I would like to pay someone to help me implement ConnectyCube Video + CallKeep + Wake App From Background + Notifications + Messages in 1 template app.
> 
> I already have implemented ConnectyCube + Callkeep.
> 
> I need help and would love to get in touch and talk about paid/free work whichever suits you?

Please, https://connectycube.com/contact/

**Comment by DaveLomber** [comment]
Closed in favour of https://github.com/ConnectyCube/connectycube-reactnative-samples/pull/200

**Pull request closed without merging**
